
-- Create new_member_classes table
create table if not exists public.new_member_classes (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  created_at timestamptz default now()
);

-- Create new_member_lessons table
create table if not exists public.new_member_lessons (
  id bigint generated by default as identity primary key,
  class_id bigint references public.new_member_classes(id) on delete cascade,
  title text not null,
  date date not null,
  completed boolean default false,
  created_at timestamptz default now()
);

-- Create new_member_class_students table
create table if not exists public.new_member_class_students (
  id bigint generated by default as identity primary key,
  class_id bigint references public.new_member_classes(id) on delete cascade,
  member_id uuid references public.members(id) on delete cascade,
  created_at timestamptz default now(),
  unique(class_id, member_id)
);

-- Create new_member_attendance table
create table if not exists public.new_member_attendance (
  id bigint generated by default as identity primary key,
  lesson_id bigint references public.new_member_lessons(id) on delete cascade,
  member_id uuid references public.members(id) on delete cascade,
  present boolean default false,
  summary_done boolean default false,
  created_at timestamptz default now(),
  unique(lesson_id, member_id)
);

-- Enable RLS
alter table public.new_member_classes enable row level security;
alter table public.new_member_lessons enable row level security;
alter table public.new_member_class_students enable row level security;
alter table public.new_member_attendance enable row level security;

-- Policies
create policy "Authenticated users can manage new member classes" on public.new_member_classes for all using (auth.role() = 'authenticated');
create policy "Authenticated users can manage new member lessons" on public.new_member_lessons for all using (auth.role() = 'authenticated');
create policy "Authenticated users can manage new member students" on public.new_member_class_students for all using (auth.role() = 'authenticated');
create policy "Authenticated users can manage new member attendance" on public.new_member_attendance for all using (auth.role() = 'authenticated');
