-- Create new_converts table
create table if not exists public.new_converts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  conversion_date date,
  mentor text, -- Could be a foreign key to members later, but keeping as text for flexibility or link to member naem
  status text check (status in ('Acompanhamento', 'Batizado', 'Integrado')) default 'Acompanhamento',
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.new_converts enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
  on public.new_converts for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.new_converts for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.new_converts for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.new_converts for delete
  using (auth.role() = 'authenticated');

-- Trigger for updated_at
create trigger handle_updated_at before update on public.new_converts
  for each row execute procedure moddatetime (updated_at);
