-- Create departments table
create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  leader text,
  members_count int default 0,
  description text,
  next_meeting text,
  budget text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.departments enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
  on public.departments for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.departments for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.departments for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.departments for delete
  using (auth.role() = 'authenticated');

-- Trigger to update updated_at
create or replace function public.handle_departments_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger departments_updated_at
  before update on public.departments
  for each row
  execute procedure public.handle_departments_updated_at();
