-- Create discipleship_groups table
create table if not exists public.discipleship_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  leader text,
  meeting_day text,
  meeting_time text,
  location text,
  members_count int default 0,
  target_audience text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.discipleship_groups enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
  on public.discipleship_groups for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.discipleship_groups for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.discipleship_groups for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.discipleship_groups for delete
  using (auth.role() = 'authenticated');

-- Trigger to update updated_at
create or replace function public.handle_discipleship_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger discipleship_updated_at
  before update on public.discipleship_groups
  for each row
  execute procedure public.handle_discipleship_updated_at();
