
-- Create sessions table
create table if not exists public.discipleship_sessions (
  id bigint generated by default as identity primary key,
  group_id bigint references public.discipleship_groups(id) on delete cascade,
  date date not null,
  lesson_name text,
  notes text,
  created_at timestamptz default now()
);

-- Create attendance table
create table if not exists public.discipleship_attendance (
  id bigint generated by default as identity primary key,
  session_id bigint references public.discipleship_sessions(id) on delete cascade,
  member_id uuid references public.members(id) on delete cascade,
  status text default 'Presente',
  created_at timestamptz default now(),
  unique(session_id, member_id)
);

-- Enable RLS
alter table public.discipleship_sessions enable row level security;
alter table public.discipleship_attendance enable row level security;

-- Policies for sessions
create policy "Enable read access for authenticated users"
  on public.discipleship_sessions for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.discipleship_sessions for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.discipleship_sessions for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.discipleship_sessions for delete
  using (auth.role() = 'authenticated');

-- Policies for attendance
create policy "Enable read access for authenticated users"
  on public.discipleship_attendance for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.discipleship_attendance for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.discipleship_attendance for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.discipleship_attendance for delete
  using (auth.role() = 'authenticated');
