-- Create junction table for discipleship group members
create table if not exists public.discipleship_members (
  id bigint generated by default as identity primary key,
  group_id bigint references public.discipleship_groups(id) on delete cascade,
  member_id uuid references public.members(id) on delete cascade,
  role text default 'Participante', -- 'Participante', 'Líder', 'Co-líder'
  joined_at timestamptz default now(),
  unique(group_id, member_id)
);

-- Enable RLS
alter table public.discipleship_members enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
  on public.discipleship_members for select
  using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users"
  on public.discipleship_members for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users"
  on public.discipleship_members for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users"
  on public.discipleship_members for delete
  using (auth.role() = 'authenticated');
